import localFont from "next/font/local"; // Import the `localFont` utility
import "./globals.css"; // Import global styles

/* Components */
import Header from "@/components/Header"; // Import the Header component

/* Load JetBrains Mono using the `localFont` utility */
const jetbrainsMono = localFont({
  src: [
    {
      path: "/fonts/JetBrainsMono-Regular.ttf",
      weight: "400",
    },
    {
      path: "/fonts/JetBrainsMono-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-jetbrainsMono", // custom CSS variable name
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
